name: data-vis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.3.2
  - ansi2html=1.9.1
  - asttokens=2.0.5
  - attr=2.5.1
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - dash=2.14.2
  - dash-bootstrap-components=1.6.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.2
  - fftw=3.3.9
  - flask=3.0.3
  - flask-compress=1.13
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gst-plugins-base=1.20.2
  - gstreamer=1.20.2
  - icu=70.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - intel-openmp=2021.4.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - itsdangerous=2.2.0
  - jack=1.9.18
  - jedi=0.18.1
  - jinja2=3.1.4
  - jpeg=9e
  - json-c=0.15
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.51
  - libclang=14.0.3
  - libclang13=14.0.3
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libevent=2.1.10
  - libffi=3.4.4
  - libflac=1.3.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.3
  - libnsl=2.0.0
  - libntlm=1.6
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.3
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.11
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mplsoccer=1.2.4
  - mysql=5.7.24
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nspr=4.35
  - nss=3.77
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=23.2
  - pandas=2.2.2
  - parso=0.8.3
  - patsy=0.5.6
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pillow=9.0.1
  - pip=24.0
  - platformdirs=3.10.0
  - plotly=5.22.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=25.1.2
  - qt-main=5.15.3
  - readline=8.2
  - requests=2.32.2
  - retrying=1.3.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.38.5
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tk=8.6.11
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.1
  - wcwidth=0.2.5
  - werkzeug=3.0.3
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
      - annotated-types==0.6.0
      - joblib==1.4.2
      - lxml==4.9.4
      - matplotsoccer==0.0.8
      - multimethod==1.11.2
      - mypy-extensions==1.0.0
      - pandera==0.17.2
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - socceraction==1.5.1
      - threadpoolctl==3.5.0
      - typeguard==4.2.1
      - typing-inspect==0.9.0
      - wrapt==1.16.0
